apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: c02-cluster-apps
  namespace: c02
  labels:
    app: c02-cluster-apps
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - c02-cluster-apps
