apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-serverless-placement-binding
  namespace: policies
placementRef:
  name: serverless-operator-placement-all-qa-c01
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: serverless-operator-policy-all-qa-c01
    apiGroup: policy.open-cluster-management.io
    kind: Policy
