apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: acm-operator-policy-demo
  namespace: acm-operator-policy-demo-ns
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  type: Git
  pathname: https://github.com/senthilredhat/acm-operator-policy-demo.git
