apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: group-subscriptions
  namespace: policies
  labels:
    app: group-subscriptions
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: app-of-app-group-subs
    apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: acm-operator-policy-demo-ns/acm-operator-policy-demo
  placement:
    placementRef:
      kind: Placement
      name: hub-cluster-placement
