apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - clusterrolebinding.yaml
  - managedclustersetbinding.yaml
  - placement.yaml
  - group-application.yaml
  - group-subscription.yaml
