apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: serverless-operator-policy
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: serverless-operator-namespace
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-serverless
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: serverless-operator
        spec:
          remediationAction: enforce
          severity: medium
          complianceType: musthave
          upgradeApproval: Automatic
          complianceConfig:
            catalogSourceUnhealthy: Compliant
            deploymentsUnavailable: NonCompliant
            upgradesAvailable: Compliant
          removalBehavior:
            clusterServiceVersions: Delete
            customResourceDefinitions: Keep
            operatorGroups: DeleteIfUnused
            subscriptions: Delete
          operatorGroup:
            name: openshift-serverless
            namespace: openshift-serverless
          subscription:
            name: serverless-operator
            namespace: openshift-serverless
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            startingCSV: serverless-operator.v1.37.1
