apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../components/gitlab-operator
  - ../../components/serverless-operator
  - placement.yaml
  - placement-binding.yaml
  - placement-serverless-operator.yaml
  - placement-binding-serverless.yaml
