apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-serverless-operator-qa
  namespace: policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            environment: qa
