apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-serverless-operator-qa
  namespace: policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-serverless-operator-qa
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: serverless-operator-policy
