apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: gitlab-wave1-group-apps
  namespace: gitlab-wave1
  labels:
    app: gitlab-wave1-group-apps
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - gitlab-wave1-group-apps
