apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: gitlab-operator-placement-binding
  namespace: policies
placementRef:
  name: gitlab-operator-placement-all-qa-c02
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: gitlab-operator-policy-all-qa-c02
    apiGroup: policy.open-cluster-management.io
    kind: Policy
