apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-gitlab-operator-prod
  namespace: policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            operator-upgrade-wave: prod
