apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: hub-cluster-placement
  namespace: policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            local-cluster: "true"
